<div class="row">
    <div class="col-sm-8"><h2>Lista de categorias</h2></div>
    <div class="col-sm-4" style="padding-top: 20px">
        <a href="<?php echo APP_URL."tareas/index"; ?>" >
            <button type="button" class="btn btn-primary add">
                <span class="glyphicon glyphicon-arrow-left"></span> Tareas
            </button>
        </a>
        <a href="<?php echo APP_URL."categorias/agregar"; ?>">
            <button type="button" class="btn btn-primary add">
                <span class="glyphicon glyphicon-plus"></span> Categoría
            </button>
        </a>
    </div>
</div>
<div class="table-responsive">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
        </tr>
        <?php foreach ($this->categorias as $categoria): ?>
            <tr>
                <td><?php echo $categoria["id"]; ?></td>
                <td><?php echo $categoria["nombre"]; ?></td>
                <td> <a href="<?php echo APP_URL."tareas/editar/".$categoria["id"]; ?>"><span class="glyphicon glyphicon-edit"></span></a>
                    <a href="<?php echo APP_URL."tareas/eliminar/".$categoria["id"]; ?>"><span class="glyphicon glyphicon-trash"></span></a>
            </tr>
        <?php endforeach; ?>

    </table>
</div>